FROM alpine:3.7

RUN apk update \
    && apk add python3 \
    && apk add py-pip

RUN pip3 install --upgrade pip setuptools

COPY . /app
WORKDIR /app

RUN pip3 install -r requirements.txt
RUN pip3 install -e ".[dev]"

CMD ["pserve", "development.ini", "--reload" ] 